export const metadata = {
  title: "EmmanuelImole Portfolio",
  description: "Generated by Next.js",
};

import "@/app/global.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/portfolio-icon.svg" type="image/svg+xml" />
      </head>

      <body>{children}</body>
    </html>
  );
}
