export const metadata = {
  title: "Emmanuel_Imole Portfolio",
  description: "Generated by Next.js",
};

// import "@/app/mobile.css";
import "@/app/media.css";
import "@/app/section.css";
import "@/app/navbar.css";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/portfolio-icon.svg" type="image/svg+xml" />
      </head>

      <body>{children}</body>
    </html>
  );
}
